export const GNB = [
  { id: 'weather', item: '날씨' },
  { id: 'fortune', item: '운세' },
  { id: 'toDo', item: '할일' },
  { id: 'diet', item: '식단' },
  { id: 'question', item: '질문' },
];

export const animation = [
  'animate-[translate_0.5s_ease_alternate]',
  'animate-[translate_0.5s_ease_alternate_0.5s]',
  'animate-[translate_0.5s_ease_alternate_0.8s]',
  'animate-[translate_0.5s_ease_alternate_1.1s]',
  'animate-[translate_0.5s_ease_alternate_1.4s]',
];

export const BASE_URL = 'http://api.openweathermap.org';

export const KEY = '323f64ab84d6fe3f4e2cce7ed99120f0';

export const WEATHER = [
  { id: 201, description: '가벼운 비와 천둥구름' },
  { id: 200, description: '비와 천둥구름' },
  { id: 202, description: '폭우와 천둥구름' },
  { id: 210, description: '약한 천둥구름' },
  { id: 211, description: '천둥구름' },
  { id: 212, description: '강한 천둥구름' },
  { id: 221, description: '불규칙적 천둥구름' },
  { id: 230, description: '약한 비와 천둥구름' },
  { id: 231, description: '가벼운 비와 천둥구름' },
  { id: 232, description: '강한 안개비와 천둥구름' },
  { id: 300, description: '가벼운 안개비' },
  { id: 301, description: '안개비' },
  { id: 302, description: '강한 안개비' },
  { id: 310, description: '가벼운 적은 비' },
  { id: 311, description: '적은비' },
  { id: 312, description: '강한 적은 비' },
  { id: 313, description: '소나기와 안개비' },
  { id: 314, description: '강한 소나기와 안개비' },
  { id: 321, description: '소나기' },
  { id: 500, description: '약한 비' },
  { id: 501, description: '중간 비' },
  { id: 502, description: '강한 비' },
  { id: 503, description: '매우 강한 비' },
  { id: 504, description: '폭우' },
  { id: 511, description: '우박' },
  { id: 520, description: '약한 소나기' },
  { id: 521, description: '소나기' },
  { id: 522, description: '강한 소나기' },
  { id: 531, description: '불규칙적 소나기' },
  { id: 600, description: '가벼운 눈' },
  { id: 601, description: '눈' },
  { id: 602, description: '강한 눈' },
  { id: 611, description: '진눈깨비' },
  { id: 612, description: '소나기 진눈깨비' },
  { id: 615, description: '약한 비와 눈' },
  { id: 616, description: '비와 눈' },
  { id: 620, description: '약한 소나기와 눈' },
  { id: 621, description: '소나기와 눈' },
  { id: 622, description: '강한 소나기와 눈' },
  { id: 701, description: '옅은 안개' },
  { id: 711, description: '연기' },
  { id: 721, description: '옅은 안개' },
  { id: 731, description: '모래 먼지' },
  { id: 741, description: '안개' },
  { id: 751, description: '모래' },
  { id: 761, description: '먼지' },
  { id: 762, description: '화산재' },
  { id: 771, description: '돌풍' },
  { id: 781, description: '토네이도' },
  { id: 800, description: '맑음' },
  { id: 801, description: '구름 조금' },
  { id: 802, description: '구름 조금 많음' },
  { id: 803, description: '구름 많음' },
  { id: 804, description: '흐림' },
  { id: 900, description: '토네이도' },
  { id: 901, description: '태풍' },
  { id: 902, description: '허리케인' },
  { id: 903, description: '한랭' },
  { id: 904, description: '고온' },
  { id: 905, description: '바람부는' },
  { id: 906, description: '우박' },
  { id: 951, description: '바람이 거의 없음' },
  { id: 952, description: '약한 바람' },
  { id: 953, description: '부드러운 바람' },
  { id: 954, description: '중간 세기 바람' },
  { id: 955, description: '맑은 바람' },
  { id: 956, description: '센 바람' },
  { id: 957, description: '돌풍에 가까운 센 바람' },
  { id: 958, description: '돌풍' },
  { id: 959, description: '심각한 돌풍' },
  { id: 960, description: '폭풍' },
  { id: 961, description: '강한 폭풍' },
  { id: 962, description: '허리케인' },
];

export const CATEGORY = [
  { id: '아침', title: '아침' },
  { id: '점심', title: '점심' },
  { id: '저녁', title: '저녁' },
];
